addpath ('/mnt/isilon/userdata/home/nwong002/Codes/')
addpath ('/mnt/isilon/userdata/home/nwong002/Codes/EQ_')
addpath ('/mnt/isilon/userdata/home/nwong002/Codes/GTdef_')
addpath ('/mnt/isilon/userdata/home/nwong002/Codes/GPS_/')
addpath ('/mnt/isilon/userdata/home/nwong002/Codes/Other/')
addpath ('/mnt/isilon/userdata/home/nwong002/Geodesy/Data/')
addpath ('/mnt/isilon/userdata/home/nwong002/Geodesy/Data/Coseismic_Offsets/')