function EQFile = EQ_create_printFile (EQtype,EQID,EQpos,EQslip)




slab = EQtype(3);  reg = EQtype(5);
date = EQID.ID(1); Mw  = EQID.ID(2); depth = floor(EQpos.z(1)/1000);
name = EQ_create_printregname (reg); mu = EQslip.MME(2);

if any(slab == [1 1.1])
    EQFile = [ 'EQ' num2str(date) '_' ...
               'Mw' num2str(Mw,'%04.2f') '_' ...
               name '_' ...
               'Rig' num2str(mu) '_co.eq' ];
else
    EQFile = [ 'EQ' num2str(date) '_' ...
               'Mw' num2str(Mw,'%04.2f') '_' ...
               num2str(depth,'%02d') 'km' '_' ...
               name '_' ...
               'Rig' num2str(mu) '_co.eq' ];
end