function [ inName ] = EQ_print_insw (xx,inmat,data)



EQID = data.EQID; EQID = strrep (EQID,'co','');
regID = data.type(5); mu = data.slip(2);
regname = EQ_create_printregname (regID);

inName = [ EQID '_' regname '_' 'Rig' num2str(mu) '_' ...
              'insw' xx '_co.txt' ];

fin = fopen (inName,'w');

fprintf (fin,'# Input DataFile for EQID: %s\n',data.EQID);
fprintf (fin,'#                   COUNT: %s\n',xx);
fprintf (fin,'#                    SIZE: S (WEIGHTED)\n\n');

fprintf (fin,'# This file contains all the relevant input data for the abovementioned\n');
fprintf (fin,'# earthquake event.  This includes the following datasets:\n');
fprintf (fin,'#     - Longitude / Latitude (d)\n');
fprintf (fin,'#     - Surface Longtitude / Latitude (d)\n');
fprintf (fin,'#     - z1 and z2 Depth (m)\n');
fprintf (fin,'#     - Strike, Dip, Rake (d)\n');
fprintf (fin,'#     - Rake-, Strike-, Dip- and Tensile-Slip (m)\n\n');

fprintf (fin,[ '# ii     ID      lon1 (d)   lat1 (d)   lon2 (d)' ...
    '   ' ... 
    'lat2 (d)   slon1 (d)   slat1 (d)   slon2 (d)   slat2 (d)' ...
    '   ' ...
    'z1 (m)    z2 (m)    str (d)   dip (d)   rake (d)' ...
    '   ' ...
    'rs (m)    ss (m)    ds (m)    ts (m)\n']);

fprintf (fin,[ '  %-4d   %-5d   %-8.3f   %-7.3f    %-8.3f   %-7.3f' ...
    '    ' ...
    '%-8.3f    %-7.3f     %-8.3f    %-7.3f     %-6.0f    %-6.0f' ...
    '    ' ...
    '%-5.1f     %-5.1f     %-5.1f' ...
    '      ' ...
    '%-7.4f   %-7.4f   %-7.4f   %-7.4f\n' ], inmat');

fclose(fin);